const books = [
  {
    id: 17001,
    title: [
      'Идеальный программист',
      'Чистый код',
      'Выразительный JavaScript',
      'The Road to React',
      'React Design Patterns and Best Practices',
      'Fullstack React',
      'Эффективный TypeScript',
      'Профессиональный TypeScript',
    ],
    link: [
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
    ],
  },
  {
    id: 17002,
    title: [
      'Идеальный программист',
      'Чистый код',
      'Выразительный JavaScript',
      'The Road to React',
      'React Design Patterns and Best Practices',
      'Fullstack React',
      'Эффективный TypeScript',
      'Профессиональный TypeScript',
    ],
    link: [
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
    ],
  },
  {
    id: 17003,
    title: [
      'Идеальный программист',
      'Чистый код',
      'Выразительный JavaScript',
      'The Road to React',
      'React Design Patterns and Best Practices',
      'Fullstack React',
      'Эффективный TypeScript',
      'Профессиональный TypeScript',
    ],
    link: [
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
    ],
  },
  {
    id: 17004,
    title: [
      'Идеальный программист',
      'Чистый код',
      'Выразительный JavaScript',
      'The Road to React',
      'React Design Patterns and Best Practices',
      'Fullstack React',
      'Эффективный TypeScript',
      'Профессиональный TypeScript',
    ],
    link: [
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
    ],
  },
  {
    id: 17005,
    title: [
      'Идеальный программист',
      'Чистый код',
      'Выразительный JavaScript',
      'The Road to React',
      'React Design Patterns and Best Practices',
      'Fullstack React',
      'Эффективный TypeScript',
      'Профессиональный TypeScript',
    ],
    link: [
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
    ],
  },
  {
    id: 17006,
    title: [
      'Идеальный программист',
      'Чистый код',
      'Выразительный JavaScript',
      'The Road to React',
      'React Design Patterns and Best Practices',
      'Fullstack React',
      'Эффективный TypeScript',
      'Профессиональный TypeScript',
    ],
    link: [
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
    ],
  },
  {
    id: 17007,
    title: [
      'Идеальный программист',
      'Чистый код',
      'Выразительный JavaScript',
      'The Road to React',
      'React Design Patterns and Best Practices',
      'Fullstack React',
      'Эффективный TypeScript',
      'Профессиональный TypeScript',
    ],
    link: [
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
      'https://www.amazon.com/',
    ],
  },
];

export default books;
