const lesson = [
  {
    id: 8001,
    title: [
      'WebDev с нуля',
      'Фрілансер по життю',
      'WebDesign Master',
      'ВебКадеми',
      'Archakov Blog',
      'RED Group',
      'Ulbi TV',
      'От 0 до 1',
      'Михаил Непомнящий',
    ],
    link: [
      'https://www.youtube.com/@itgid',
      'https://www.youtube.com/@FreelancerLifeStyle',
      'https://www.youtube.com/@wdm',
      'https://www.youtube.com/@WebCademy',
      'https://www.youtube.com/@ArchakovBlog',
      'https://www.youtube.com/@REDGroup',
      'https://www.youtube.com/@UlbiTV',
      'https://www.youtube.com/@vadymprokopchuk',
      'https://www.youtube.com/@mishanep',
    ],
  },
  {
    id: 8002,
    title: [
      'WebDev с нуля',
      'Фрілансер по життю',
      'WebDesign Master',
      'ВебКадеми',
      'Archakov Blog',
      'RED Group',
      'Ulbi TV',
      'От 0 до 1',
      'Михаил Непомнящий',
    ],
    link: [
      'https://www.youtube.com/@itgid',
      'https://www.youtube.com/@FreelancerLifeStyle',
      'https://www.youtube.com/@wdm',
      'https://www.youtube.com/@WebCademy',
      'https://www.youtube.com/@ArchakovBlog',
      'https://www.youtube.com/@REDGroup',
      'https://www.youtube.com/@UlbiTV',
      'https://www.youtube.com/@vadymprokopchuk',
      'https://www.youtube.com/@mishanep',
    ],
  },
  {
    id: 8003,
    title: [
      'WebDev с нуля',
      'Фрілансер по життю',
      'WebDesign Master',
      'ВебКадеми',
      'Archakov Blog',
      'RED Group',
      'Ulbi TV',
      'От 0 до 1',
      'Михаил Непомнящий',
    ],
    link: [
      'https://www.youtube.com/@itgid',
      'https://www.youtube.com/@FreelancerLifeStyle',
      'https://www.youtube.com/@wdm',
      'https://www.youtube.com/@WebCademy',
      'https://www.youtube.com/@ArchakovBlog',
      'https://www.youtube.com/@REDGroup',
      'https://www.youtube.com/@UlbiTV',
      'https://www.youtube.com/@vadymprokopchuk',
      'https://www.youtube.com/@mishanep',
    ],
  },
  {
    id: 8004,
    title: [
      'WebDev с нуля',
      'Фрілансер по життю',
      'WebDesign Master',
      'ВебКадеми',
      'Archakov Blog',
      'RED Group',
      'Ulbi TV',
      'От 0 до 1',
      'Михаил Непомнящий',
    ],
    link: [
      'https://www.youtube.com/@itgid',
      'https://www.youtube.com/@FreelancerLifeStyle',
      'https://www.youtube.com/@wdm',
      'https://www.youtube.com/@WebCademy',
      'https://www.youtube.com/@ArchakovBlog',
      'https://www.youtube.com/@REDGroup',
      'https://www.youtube.com/@UlbiTV',
      'https://www.youtube.com/@vadymprokopchuk',
      'https://www.youtube.com/@mishanep',
    ],
  },
  {
    id: 8005,
    title: [
      'WebDev с нуля',
      'Фрілансер по життю',
      'WebDesign Master',
      'ВебКадеми',
      'Archakov Blog',
      'RED Group',
      'Ulbi TV',
      'От 0 до 1',
      'Михаил Непомнящий',
    ],
    link: [
      'https://www.youtube.com/@itgid',
      'https://www.youtube.com/@FreelancerLifeStyle',
      'https://www.youtube.com/@wdm',
      'https://www.youtube.com/@WebCademy',
      'https://www.youtube.com/@ArchakovBlog',
      'https://www.youtube.com/@REDGroup',
      'https://www.youtube.com/@UlbiTV',
      'https://www.youtube.com/@vadymprokopchuk',
      'https://www.youtube.com/@mishanep',
    ],
  },
  {
    id: 8006,
    title: [
      'WebDev с нуля',
      'Фрілансер по життю',
      'WebDesign Master',
      'ВебКадеми',
      'Archakov Blog',
      'RED Group',
      'Ulbi TV',
      'От 0 до 1',
      'Михаил Непомнящий',
    ],
    link: [
      'https://www.youtube.com/@itgid',
      'https://www.youtube.com/@FreelancerLifeStyle',
      'https://www.youtube.com/@wdm',
      'https://www.youtube.com/@WebCademy',
      'https://www.youtube.com/@ArchakovBlog',
      'https://www.youtube.com/@REDGroup',
      'https://www.youtube.com/@UlbiTV',
      'https://www.youtube.com/@vadymprokopchuk',
      'https://www.youtube.com/@mishanep',
    ],
  },
  {
    id: 8007,
    title: [
      'WebDev с нуля',
      'Фрілансер по життю',
      'WebDesign Master',
      'ВебКадеми',
      'Archakov Blog',
      'RED Group',
      'Ulbi TV',
      'От 0 до 1',
      'Михаил Непомнящий',
    ],
    link: [
      'https://www.youtube.com/@itgid',
      'https://www.youtube.com/@FreelancerLifeStyle',
      'https://www.youtube.com/@wdm',
      'https://www.youtube.com/@WebCademy',
      'https://www.youtube.com/@ArchakovBlog',
      'https://www.youtube.com/@REDGroup',
      'https://www.youtube.com/@UlbiTV',
      'https://www.youtube.com/@vadymprokopchuk',
      'https://www.youtube.com/@mishanep',
    ],
  },
];

export default lesson;
