const sites = [
  {
    id: 17001,
    title: [
      'web.dev CSS',
      'web.dev HTML',
      'ReactJS best practices',
      'TypeScript',
      'w3schools TS',
      'w3schools SCSS',
      'w3schools GIT',
      'w3schools REACT JS',
      'Django (why not)',
    ],
    link: [
      'https://web.dev/learn/css/',
      'https://web.dev/learn/html/',
      'https://kinsta.com/blog/react-best-practices/#react-best-practices',
      'https://www.typescriptlang.org/docs/',
      'https://www.w3schools.com/typescript/',
      'https://www.w3schools.com/sass/default.php',
      'https://www.w3schools.com/git/default.asp',
      'https://www.w3schools.com/react/default.asp',
      'https://www.w3schools.com/django/index.php',
    ],
  },
  {
    id: 17002,
    title: [
      'web.dev CSS',
      'web.dev HTML',
      'ReactJS best practices',
      'TypeScript',
      'w3schools TS',
      'w3schools SCSS',
      'w3schools GIT',
      'w3schools REACT JS',
      'Django (why not)',
    ],
    link: [
      'https://web.dev/learn/css/',
      'https://web.dev/learn/html/',
      'https://kinsta.com/blog/react-best-practices/#react-best-practices',
      'https://www.typescriptlang.org/docs/',
      'https://www.w3schools.com/typescript/',
      'https://www.w3schools.com/sass/default.php',
      'https://www.w3schools.com/react/default.asp',
      'https://www.w3schools.com/django/index.php',
    ],
  },
  {
    id: 17003,
    title: [
      'web.dev CSS',
      'web.dev HTML',
      'ReactJS best practices',
      'TypeScript',
      'w3schools TS',
      'w3schools SCSS',
      'w3schools GIT',
      'w3schools REACT JS',
      'Django (why not)',
    ],
    link: [
      'https://web.dev/learn/css/',
      'https://web.dev/learn/html/',
      'https://kinsta.com/blog/react-best-practices/#react-best-practices',
      'https://www.typescriptlang.org/docs/',
      'https://www.w3schools.com/typescript/',
      'https://www.w3schools.com/sass/default.php',
      'https://www.w3schools.com/react/default.asp',
      'https://www.w3schools.com/django/index.php',
    ],
  },
  {
    id: 17004,
    title: [
      'web.dev CSS',
      'web.dev HTML',
      'ReactJS best practices',
      'TypeScript',
      'w3schools TS',
      'w3schools SCSS',
      'w3schools GIT',
      'w3schools REACT JS',
      'Django (why not)',
    ],
    link: [
      'https://web.dev/learn/css/',
      'https://web.dev/learn/html/',
      'https://kinsta.com/blog/react-best-practices/#react-best-practices',
      'https://www.typescriptlang.org/docs/',
      'https://www.w3schools.com/typescript/',
      'https://www.w3schools.com/sass/default.php',
      'https://www.w3schools.com/react/default.asp',
      'https://www.w3schools.com/django/index.php',
    ],
  },
  {
    id: 17005,
    title: [
      'web.dev CSS',
      'web.dev HTML',
      'ReactJS best practices',
      'TypeScript',
      'w3schools TS',
      'w3schools SCSS',
      'w3schools GIT',
      'w3schools REACT JS',
      'Django (why not)',
    ],
    link: [
      'https://web.dev/learn/css/',
      'https://web.dev/learn/html/',
      'https://kinsta.com/blog/react-best-practices/#react-best-practices',
      'https://www.typescriptlang.org/docs/',
      'https://www.w3schools.com/typescript/',
      'https://www.w3schools.com/sass/default.php',
      'https://www.w3schools.com/react/default.asp',
      'https://www.w3schools.com/django/index.php',
    ],
  },
  {
    id: 17006,
    title: [
      'web.dev CSS',
      'web.dev HTML',
      'ReactJS best practices',
      'TypeScript',
      'w3schools TS',
      'w3schools SCSS',
      'w3schools GIT',
      'w3schools REACT JS',
      'Django (why not)',
    ],
    link: [
      'https://web.dev/learn/css/',
      'https://web.dev/learn/html/',
      'https://kinsta.com/blog/react-best-practices/#react-best-practices',
      'https://www.typescriptlang.org/docs/',
      'https://www.w3schools.com/typescript/',
      'https://www.w3schools.com/sass/default.php',
      'https://www.w3schools.com/react/default.asp',
      'https://www.w3schools.com/django/index.php',
    ],
  },
  {
    id: 17007,
    title: [
      'web.dev CSS',
      'web.dev HTML',
      'ReactJS best practices',
      'TypeScript',
      'w3schools TS',
      'w3schools SCSS',
      'w3schools GIT',
      'w3schools REACT JS',
      'Django (why not)',
    ],
    link: [
      'https://web.dev/learn/css/',
      'https://web.dev/learn/html/',
      'https://kinsta.com/blog/react-best-practices/#react-best-practices',
      'https://www.typescriptlang.org/docs/',
      'https://www.w3schools.com/typescript/',
      'https://www.w3schools.com/sass/default.php',
      'https://www.w3schools.com/react/default.asp',
      'https://www.w3schools.com/django/index.php',
    ],
  },
];

export default sites;
