const DataTask = [
  {
    id: 1232,
    title: [
      'Создайте HTML-страницу с формой обратной связи, содержащей поля для имени, электронной почты и сообщения.',
      'Создайте HTML-страницу с таблицей, содержащей информацию о различных продуктах, такую как название, цена и описание.',
      'Создайте HTML-страницу с галереей изображений, где каждое изображение можно щелкнуть для увеличения.',
      'Создайте HTML-страницу с выпадающим меню, содержащим список различных категорий.',
      'Создайте HTML-страницу с видеоплеером, который воспроизводит видеофайл с использованием тега <video>.',
      'Создайте HTML-страницу с анимацией, используя CSS-анимации или JavaScript.',
    ],
    titleENG: [
      'Create an HTML page with a feedback form, containing fields for name, email, and message.',
      'Create an HTML page with a table that displays information about different products, such as name, price, and description.',
      'Create an HTML page with an image gallery, where each image can be clicked to enlarge.',
      'Create an HTML page with a dropdown menu containing a list of different categories.',
      'Create an HTML page with a video player that plays a video file using the <video> tag.',
      'Create an HTML page with an animation using CSS animations or JavaScript.',
    ],
  },
  {
    id: 4123,
    title: [
      'Создание стилизованной навигационной панели: Создайте горизонтальную или вертикальную навигационную панель с использованием CSS. Примените стили к элементам меню, таким как фоновый цвет, шрифты, отступы и эффекты при наведении курсора. Обеспечьте активное состояние для текущего элемента меню.',
      'Разработка адаптивного макета: Создайте адаптивный макет, который корректно отображается на различных устройствах и разрешениях экрана. Используйте медиа-запросы и флексбоксы или сетки для создания гибкого макета, который адаптируется к изменениям размера экрана. Учтите различные факторы, такие как растягивание изображений, скрытие некритических элементов и изменение расположения контента.',
      'Создание анимации: Разработайте анимацию элементов на странице с использованием CSS. Примените переходы, ключевые кадры или анимацию transform для создания плавных и эффектных переходов или изменений состояний элементов. Используйте события, такие как наведение курсора или клик, для запуска анимации.',
      'Стилизация формы: Создайте стилизованную форму с использованием CSS. Измените внешний вид элементов формы, таких как текстовые поля, флажки, радиокнопки и кнопки отправки. Примените стили к состояниям элементов формы, таким как фокус, наведение и ошибки валидации. ',
      'Создайте адаптивное меню бургера, которое отображается в виде иконки на маленьких экранах. При нажатии на иконку меню, показывайте или скрывайте навигационное меню с использованием анимации. Обеспечьте корректное отображение и функциональность меню на различных устройствах.',
      'Создание стилизованных карточек контента: Разработайте стилизованные карточки для отображения контента, такого как статьи, продукты или профили пользователей. Примените стили к элементам карточки, таким как фоновый цвет, тени',
    ],
    titleENG: [
      'Create a styled navbar: Create a horizontal or vertical navbar using CSS. Apply styles to menu items such as background color, fonts, padding, and hover effects. Provide an active state for the current menu item.',
      'Responsive layout development: Design a responsive layout that displays correctly on various devices and screen resolutions. Use media queries and flexbox or grids to create a flexible layout that adapts to screen size changes. Consider various factors such as stretching images, hiding non-critical elements, and repositioning content.',
      'Creating Animations: Animate elements on the page using CSS. Apply transitions, keyframes, or transform animations to create smooth and dramatic transitions or element state changes. Use events like hover or click to trigger the animation.',
      'Form Styling: Create a styled form using CSS. Change the appearance of form elements such as text fields, checkboxes, radio buttons, and submit buttons. Apply styles to form element states such as focus, hover, and validation errors.',
      'Create a responsive burger menu that displays as an icon on small screens. When clicking on the menu icon, show or hide the navigation menu using animation. Ensure correct display and functionality of the menu on various devices.',
      'Create stylized content cards: Design stylized cards to display content such as articles, products, or user profiles. Apply styles to card elements such as background color, shadows',
    ],
  },
  {
    id: 3453,
    title: [
      'Создание функции-валидатора: Напишите функцию, которая принимает входное значение и проверяет, является ли оно допустимым (например, проверка на число, длину строки или формат электронной почты). Обработайте различные сценарии ошибок и возвращайте соответствующие сообщения или значения.',
      'Разработка функции для обработки массива данных: Напишите функцию, которая принимает массив данных и выполняет определенные операции над ним (например, фильтрацию, сортировку, поиск или преобразование). Обеспечьте гибкость и настраиваемость функции, чтобы она могла принимать различные параметры для выполнения операций над данными.',
      'Реализация функции аутентификации: Напишите функцию, которая проверяет учетные данные пользователя (например, логин и пароль) и возвращает соответствующий результат (успешная аутентификация или ошибка). Используйте хэширование паролей для безопасного хранения и сравнения паролей.',
      'Создание функции-генератора случайных чисел: Напишите функцию, которая генерирует случайное число в заданном диапазоне или с определенными параметрами (например, целое число, десятичная дробь или число с фиксированным количеством знаков после запятой). Обеспечьте возможность повторного использования функции и генерации нескольких случайных чисел.',
      'Разработка функции для работы с датами: Напишите функцию, которая выполняет операции с датами, такие как вычисление разницы между двумя датами, форматирование даты или добавление/вычитание определенного количества времени. Учтите различные форматы даты и обработку ошибок при вводе некорректных данных.',
      'Создание функции для манипуляции DOM: Напишите функцию, которая выполняет манипуляции с элементами DOM (например, добавление/удаление классов, изменение содержимого элементов, обработка событий и анимации). Обеспечьте гибкость функции, чтобы она могла применяться к различным элементам и сценариям использования. Надеюсь, эти задачи помогут вам развить навыки программирования.',
    ],
    titleENG: [
      'Creating a validator function. Handle various error scenarios and return messages or values.',
      'Developing a Function to Process an Array of Data: Write a function that takes an array of data and performs certain operations on it (such as filtering, sorting, searching, or transforming). Make the function flexible and customizable so that it can take different parameters to perform operations on the data.',
      'Implementing an Authentication Function: Write a function that validates the user"s credentials (such as login and password) and returns the appropriate result (success or failure). Use password hashing to securely store and compare passwords.',
      'Creating a random number generator function: Write a function that generates a random number in a given range or with certain parameters (for example, an integer, a decimal, or a number with a fixed number of decimal places). Provide the ability to reuse the function and generate multiple random numbers.',
      'Developing a date function: Write a function that performs operations on dates, such as calculating the difference between two dates, formatting a date, or adding/subtracting a certain amount of time. Be aware of different date formats and error handling when entering incorrect data.',
      'Creating a Function to Manipulate the DOM: Write a function that performs manipulations on DOM elements (eg adding/removing classes, changing element contents, handling events and animations). Make the function flexible so that it can be applied to different elements and use cases. I hope these tasks will help you develop your programming skills.',
    ],
  },
  {
    id: 4455,
    title: [
      'Создание компонента формы: Разработайте компонент формы с несколькими входными полями, такими как текстовые поля, флажки и кнопка отправки. Добавьте валидацию входных данных, чтобы проверять правильность заполнения полей. Обработайте отправку формы и выполните соответствующие действия при успешной отправке или при возникновении ошибок.',
      'Разработка интерактивной карусели: Создайте компонент карусели, который отображает набор изображений и позволяет пользователю прокручивать их горизонтально. Добавьте кнопки управления для перемещения вперед и назад по карусели. Реализуйте возможность автоматической прокрутки изображений через определенный интервал времени.',
      'Создание компонента модального окна: Разработайте компонент модального окна, который отображает дополнительную информацию или позволяет пользователю выполнить определенное действие. Добавьте возможность открывать и закрывать модальное окно по запросу пользователя. Обеспечьте возможность настройки содержимого модального окна для разных сценариев использования.',
      'Реализация фильтрации и сортировки данных: Создайте компонент, который отображает список элементов данных, например, список продуктов или задач. Разработайте возможность фильтрации и сортировки списка на основе различных параметров, таких как цена, дата или категория. Обновляйте отображаемый список в реальном времени при изменении параметров фильтрации или сортировки.',
      'Интеграция с API: Используйте JavaScript для выполнения HTTP-запросов к API. Разработайте компонент, который получает данные с сервера через API и отображает их пользователю. Реализуйте обработку ошибок и отображение загрузочного состояния при ожидании ответа от сервера.',
      'Создание интерфейса для аутентификации: Разработайте интерфейс, который позволяет пользователям регистрироваться, входить в систему и выходить из нее. Реализуйте проверку правильности заполнения полей при регистрации и входе. Храните данные аутентификации в безопасном формате (например, с использованием хэширования паролей). Надеюсь, эти задачи помогут вам развить навыки frontend разработки с использованием JavaScript и ReactJS. Успехов!',
    ],
    titleENG: [
      'Creating a form component: Design a form component with multiple input fields such as text fields, checkboxes, and a submit button. Add input validation to check if the fields are filled in correctly. Handle the form submission and take appropriate action on successful submission or errors.',
      'Developing an interactive carousel: Create a carousel component that displays a set of images and allows the user to scroll horizontally. Add control buttons to move forward and backward on the carousel. Implement the ability to automatically scroll images after a certain time interval.',
      'Creating a modal window component: Design a modal window component that displays additional information or allows the user to perform a specific action. Add the ability to open and close a modal window at the user"s request. Provide the ability to customize the content of the modal for different use cases.',
      'Implementing data filtering and sorting: Create a component that displays a list of data items, such as a list of products or tasks. Develop the ability to filter and sort the list based on various parameters such as price, date, or category. Update the displayed list in real time when filtering or sorting options change.',
      'API integration: Use JavaScript to make HTTP requests to the API. Develop a component that receives data from the server via an API and displays it to the user. Implement error handling and show a boot state while waiting for a response from the server.',
      'Creating an interface for authentication: Design an interface that allows users to register, log in, and log out. Implement validation of fields filled in during registration and login. Store authentication data in a secure format (for example, using password hashing). I hope these tasks will help you develop frontend development skills using JavaScript and ReactJS. Good luck!',
    ],
  },
  {
    id: 3466,
    title: [
      'Создать новый репозиторий на GitHub.',
      'Клонировать существующий репозиторий на локальный компьютер.',
      'Создать новую ветку и переключиться на нее.',
      'Добавить изменения в индекс и зафиксировать коммит.',
      'Отправить изменения в удаленный репозиторий.',
      'Обновить локальный репозиторий изменениями из удаленного репозитория.',
    ],
    titleENG: [
      'Create a new repository on GitHub.',
      'Clone an existing repository to your local machine.',
      'Create a new branch and switch to it.',
      'Add changes to the index and commit them.',
      'Push changes to a remote repository.',
      'Update your local repository with changes from a remote repository.',
    ],
  },
  {
    id: 3644,
    title: [
      'Создать класс для представления автомобиля.',
      'Реализовать интерфейс для работы с базой данных.',
      'Написать функцию для сортировки массива чисел.',
      'Разработать модуль для работы с файлами.',
      'Создать абстрактный класс для разных типов животных.',
      'Использовать декораторы для добавления функциональности в класс.',
    ],
    titleENG: [
      'Create a class to represent a car.',
      'Implement an interface for working with a database.',
      'Write a function to sort an array of numbers.',
      'Develop a module for working with files.',
      'Create an abstract class for different types of animals.',
      'Use decorators to add functionality to a class.',
    ],
  },
  {
    id: 4456,
    title: [
      'Создать конфигурационный файл для Webpack.',
      'Настроить Webpack для сборки проекта с использованием Babel.',
      'Добавить плагин для минификации JavaScript-кода.',
      'Создать несколько точек входа в проект и настроить их сборку.',
      'Добавить плагин для копирования статических файлов при сборке.',
      'Использовать Webpack для сборки проекта с использованием CSS-препроцессора.',
      'Создать файл для описания задач Gulp.',
      'Добавить задачу для компиляции Sass в CSS.',
      'Добавить задачу для минификации CSS-кода.',
      'Создать задачу для сборки проекта из нескольких файлов.',
      'Добавить задачу для копирования статических файлов в папку сборки.',
      'Использовать Gulp для автоматической перезагрузки страницы при изменении файлов проекта.',
    ],
    titleENG: [
      'Create a configuration file for Webpack.',
      'Configure Webpack to build a project using Babel.',
      'Add a plugin to minify JavaScript code.',
      'Create multiple entry points in a project and configure their build.',
      'Add a plugin to copy static files during the build.',
      'Use Webpack to build a project using a CSS preprocessor.',
      'Create a file to describe Gulp tasks.',
      'Add a task to compile Sass into CSS.',
      'Add a task to minify CSS code.',
      'Create a task to build a project from multiple files.',
      'Add a task to copy static files to the build folder.',
      'Use Gulp to automatically reload the page when project files change.',
    ],
  },
];

export default DataTask;
